envoyer_message:
    path: /messages/creer/{id}
    defaults: { _controller: MafiaMessageBundle:Message:creationMessage, id:1 }

liste_messages:
    path: /messages/liste
    defaults: { _controller: MafiaMessageBundle:Message:affichageMessages }

repondre_message:
    path: /messages/repondre
    defaults: { _controller: MafiaMessageBundle:Message:repondreMessage }
    requirements:
      _method: POST