parameters:
#    mafia_message.example.class: Mafia\MessageBundle\Example

services:
#    mafia_message.example:
#        class: %mafia_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
