<?php

namespace Mafia\FamilleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DemandeEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeEntreeRepository extends EntityRepository
{
}
