<?php

namespace Mafia\ModerationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannissementRepository extends EntityRepository
{
}
