<?php

namespace Mafia\ModerationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SurveillanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveillanceRepository extends EntityRepository
{
}
