parameters:
#    mafia_user.example.class: Mafia\UserBundle\Example

services:
#    mafia_user.example:
#        class: %mafia_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
