vue_composition:
    path: /composition/afficher/{id}
    defaults: { _controller: MafiaRolesBundle:Composition:affichageComposition, id:1 }

creation_composition:
    path: /composition/creation
    defaults: { _controller: MafiaRolesBundle:Composition:creationComposition }

ajout_compo:
    path: /composition/ajout
    defaults: { _controller: MafiaRolesBundle:Composition:ajoutComposition }
    requirements:
      _method: POST

recuperer_noms_options:
    path: /options/noms
    defaults: { _controller: MafiaRolesBundle:Composition:recupererNomOptions }
    requirements:
      _method: POST

change_valeur_option:
    path: /options/valeur
    defaults: { _controller: MafiaRolesBundle:Composition:changerOptionRoleCompo }
    requirements:
      _method: POST

recuperer_valeur_importance:
    path: /importance/recupValeur
    defaults: { _controller: MafiaRolesBundle:Composition:recupererValeurImportance }
    requirements:
      _method: POST

changer_valeur_importance:
    path: /importance/changerValeur
    defaults: { _controller: MafiaRolesBundle:Composition:changerValeurImportance }
    requirements:
      _method: POST

liste_compositions:
    path: /composition/liste
    defaults: { _controller: MafiaRolesBundle:Composition:affichageListeCompositions }

action_nuit_1:
    path: /nuit/action1
    defaults: { _controller: MafiaRolesBundle:Default:nuit }
    requirements:
      _method: POST

changer_nom_compo:
    path: /composition/nom
    defaults: { _controller: MafiaRolesBundle:Composition:changerNom }
    requirements:
      _method: POST

ajout_role_compo:
    path: /composition/role
    defaults: { _controller: MafiaRolesBundle:Composition:ajoutRoleCompo }
    requirements:
      _method: POST

modifier_composition:
    path: /composition/modification/{id}
    defaults: { _controller: MafiaRolesBundle:Composition:modificationComposition }

routing_roles:
    resource: "@MafiaRolesBundle/Resources/config/routing_roles.yml"
    prefix:   /