creation_crime:
    path: /crime/creation
    defaults: { _controller: MafiaRolesBundle:Crime:creationCrime }

liste_crimes:
    path: /crime/liste
    defaults: { _controller: MafiaRolesBundle:Crime:affichageListeCrimes }

creation_categorie:
    path: /categorie/creation
    defaults: { _controller: MafiaRolesBundle:Categorie:creationCategorie }

liste_categories:
    path: /categorie/liste
    defaults: { _controller: MafiaRolesBundle:Categorie:affichageListeCategories }

creation_role:
    path: /role/creation
    defaults: { _controller: MafiaRolesBundle:Role:creationRole }

vue_role:
    path: /role/afficher/{id}
    defaults: { _controller: MafiaRolesBundle:Role:affichageRole, id:1 }

vue_composition:
    path: /composition/afficher/{id}
    defaults: { _controller: MafiaRolesBundle:Composition:affichageComposition, id:1 }

liste_roles:
    path: /role/liste
    defaults: { _controller: MafiaRolesBundle:Role:affichageListeRoles }

creation_composition:
    path: /composition/creation
    defaults: { _controller: MafiaRolesBundle:Composition:creationComposition }

ajout_compo:
    path: /composition/ajout
    defaults: { _controller: MafiaRolesBundle:Composition:ajoutComposition }
    requirements:
      _method: POST

recuperer_noms_options:
    path: /options/noms
    defaults: { _controller: MafiaRolesBundle:Composition:recupererNomOptions }
    requirements:
      _method: POST

liste_compositions:
    path: /composition/liste
    defaults: { _controller: MafiaRolesBundle:Composition:affichageListeCompositions }

action_nuit_1:
    path: /nuit/action1
    defaults: { _controller: MafiaRolesBundle:Default:nuit }
    requirements:
      _method: POST