parameters:
#    mafia_roles.example.class: Mafia\RolesBundle\Example

services:
    mafia_roles.mafia_controller:
        class: Mafia\RolesBundle\Controller\MafiaController
#        arguments: [@service_id, "plain_value", %parameter%]
