parameters:
#    mafia_roles.example.class: Mafia\RolesBundle\Example

services:
#    mafia_roles.example:
#        class: %mafia_roles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
