parameters:
#    mafia_chat.example.class: Mafia\ChatBundle\Example

services:
#    mafia_chat.example:
#        class: %mafia_chat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    chat:
        class: Mafia\ChatBundle\Entity\Chat
        arguments:
            - @doctrine.orm.default_entity_manager