mafia_famille:
    resource: "@MafiaFamilleBundle/Resources/config/routing.yml"
    prefix:   /

mafia_partie:
    resource: "@MafiaPartieBundle/Resources/config/routing.yml"
    prefix:   /

mafia_user:
    resource: "@MafiaUserBundle/Resources/config/routing.yml"
    prefix:   /

mafia_roles:
    resource: "@MafiaRolesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"