parameters:
#    mafia_famille.example.class: Mafia\FamilleBundle\Example

services:
#    mafia_famille.example:
#        class: %mafia_famille.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
