<?php

namespace Mafia\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessagePriveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagePriveRepository extends EntityRepository
{
}
