tableau_moderation:
    path:     /moderation/tableau
    defaults: { _controller: MafiaModerationBundle:Moderation:tableauModeration }

creation_requete:
    path:     /requete/creer
    defaults: { _controller: MafiaModerationBundle:Requete:creationRequete }

vos_requetes:
    path:     /requete/liste
    defaults: { _controller: MafiaModerationBundle:Requete:listeVosRequetes }

requetes_ouvertes:
    path:     /moderation/requetes
    defaults: { _controller: MafiaModerationBundle:Requete:listeRequetesEnCours }

bannissements_user:
    path:     /moderation/bans/user/{id}/{page}
    defaults: { _controller: MafiaModerationBundle:Bannissement:listeBannissementsUser, page:1 }

bannissements:
    path:     /moderation/bans/tout/{page}
    defaults: { _controller: MafiaModerationBundle:Bannissement:listeBannissements, page:1 }