parameters:
#    mafia_moderation.example.class: Mafia\ModerationBundle\Example

services:
#    mafia_moderation.example:
#        class: %mafia_moderation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
