creation_parametres:
    path:     /parametres/creation
    defaults: { _controller: MafiaPartieBundle:Default:creationParametres }

vue_parametres:
    path: /parametres/afficher/{id}
    defaults: { _controller: MafiaPartieBundle:Default:affichageParametres, id:1 }

liste_parametres:
    path:     /parametres/liste
    defaults: { _controller: MafiaPartieBundle:Default:affichageListeParametres }

supprimer_parametres:
    path:     /parametres/supprimer/{id}
    defaults: { _controller: MafiaPartieBundle:Default:supprimerParametres, id:1 }

choix_type_partie:
    path: /jouer
    defaults: { _controller: MafiaPartieBundle:Partie:choixTypePartie }

jouer_classique:
    path: /jouer/classique
    defaults: { _controller: MafiaPartieBundle:Partie:jouerClassique }

chat_message:
    path: /chat/message
    defaults: { _controller: MafiaPartieBundle:Chat:envoyerMessage }

chat_message_recevoir:
    path: /chat/message_recevoir
    defaults: { _controller: MafiaPartieBundle:Chat:recevoirMessage }

jeu:
    path: /jeu/
    defaults: { _controller: MafiaPartieBundle:Jeu:debutPartie }

lancer_partie:
    path: /jouer/lancer
    defaults: { _controller: MafiaPartieBundle:Partie:lancerPartie }