creation_parametres:
    path:     /parametres/creation
    defaults: { _controller: MafiaPartieBundle:Default:creationParametres }

voter_pour:
    path: /jeu/vote
    defaults: { _controller: MafiaPartieBundle:Jour:voterPour }
    requirements:
      _method: POST

vue_parametres:
    path: /parametres/afficher/{id}
    defaults: { _controller: MafiaPartieBundle:Default:affichageParametres, id:1 }

liste_parametres:
    path:     /parametres/liste
    defaults: { _controller: MafiaPartieBundle:Default:affichageListeParametres }

supprimer_parametres:
    path:     /parametres/supprimer/{id}
    defaults: { _controller: MafiaPartieBundle:Default:supprimerParametres, id:1 }

choix_type_partie:
    path: /jouer
    defaults: { _controller: MafiaPartieBundle:Partie:choixTypePartie }

jouer_classique:
    path: /jouer/classique
    defaults: { _controller: MafiaPartieBundle:Partie:jouerClassique }

jouer_test:
    path: /jouer/test
    defaults: { _controller: MafiaPartieBundle:Partie:jouerTest }

chat_message:
    path: /chat/message
    defaults: { _controller: MafiaPartieBundle:Chat:envoyerMessage }

chat_message_recevoir:
    path: /chat/message_recevoir
    defaults: { _controller: MafiaPartieBundle:Chat:recevoirMessage }

jeu:
    path: /jeu
    defaults: { _controller: MafiaPartieBundle:Jeu:debutPartie }

lancer_partie:
    path: /jouer/lancer
    defaults: { _controller: MafiaPartieBundle:Partie:lancerPartie }

demande_info_aube:
    path: /jeu/aube
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsAube }
    requirements:
      _method: POST

demande_info_nuit:
    path: /jeu/nuit
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsNuit }
    requirements:
      _method: POST

demande_info_jour:
    path: /jeu/jour
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsJour }
    requirements:
      _method: POST

demande_info_discussion:
    path: /jeu/discussion
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsDiscussion }
    requirements:
      _method: POST

demande_info_tribunal_defense:
    path: /jeu/tribunal/defense
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsTribunalDefense }
    requirements:
      _method: POST

demande_info_tribunal_vote:
    path: /jeu/tribunal/vote
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsTribunalVote }
    requirements:
      _method: POST

demande_info_vote_resultat:
    path: /jeu/resultat/vote
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsVoteResultat }
    requirements:
      _method: POST

demande_info_execution:
    path: /jeu/execution
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirInformationsExecution }
    requirements:
      _method: POST

demande_duree:
    path: /jeu/duree
    defaults: { _controller: MafiaPartieBundle:Jeu:recevoirDuree }
    requirements:
      _method: POST

changer_param:
    path: /jouer/changer_parametres
    defaults: { _controller: MafiaPartieBundle:Partie:changerParametres }

changer_compo:
    path: /jouer/changer_composition
    defaults: { _controller: MafiaPartieBundle:Partie:changerComposition }

get_composition:
    path: /jouer/get_composition
    defaults: { _controller: MafiaPartieBundle:Partie:getComposition }

quitter_partie:
    path: /jouer/quitter_partie
    defaults: { _controller: MafiaPartieBundle:Partie:quitterPartie }

suicide:
    path: /jouer/suicide
    defaults: { _controller: MafiaPartieBundle:Jeu:suicide }

last_word:
    path: /jeu/lastWord
    defaults: { _controller: MafiaPartieBundle:Jeu:lastWord }
    requirements:
      _method: POST

death_note:
    path: /jeu/deathNote
    defaults: { _controller: MafiaPartieBundle:Jeu:deathNote }
    requirements:
      _method: POST

message_ig:
    path: /chat/message_ig
    defaults: { _controller: MafiaPartieBundle:Jeu:envoyerMessageIG }