parameters:
#    mafia_partie.example.class: Mafia\PartieBundle\Example

services:
    recuperation_composition:
        class: Mafia\PartieBundle\Service\RecupCompo
        arguments: [@doctrine.orm.default_entity_manager]