parameters:
#    mafia_partie.example.class: Mafia\PartieBundle\Example

services:
#    mafia_partie.example:
#        class: %mafia_partie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
