<?php

namespace Mafia\RolesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrimeRepository extends EntityRepository
{
}
