<?php
/**
 * Created by PhpStorm.
 * User: Utilisateur
 * Date: 15/01/2015
 * Time: 22:39
 */

namespace Mafia\RolesBundle\Entity;


abstract class OptionsRolesEnum {


    //-- VILLE --\\

    // SHERRIF \\

    const SHERIFF_DETECT_MAFIA_TRIADE = 0;
    const SHERIFF_DETECT_TUEUR_EN_SERIE = 1;
    const SHERIFF_DETECT_TUEUR_DE_MASSE = 2;
    const SHERIFF_DETECT_PYROMANE = 3;
    const SHERIFF_DETECT_CULTE = 4;

    // CITOYEN \\

    const CITOYEN_GILET_PARE_BALLE = 5;
    const CITOYEN_VICTOIRE_EGALITE_MAFIA = 6;

    // DOCTEUR \\

    const DOCTEUR_SAIT_CIBLE_ATTAQUEE = 7;
    const DOCTEUR_EMPECHE_CONVERSION_CULTE = 8;
    const DOCTEUR_SAIT_CONVERTI_CULTE = 9;
    const DOCTEUR_DEVIENT_SORCIER_SI_CULTE = 10;

    // MARSHALL \\

    const MARSHALL_NOMBRE_LYNCHAGE = 11;
    const MARSHALL_NOMBRE_MORT_PAR_LYNCHAGE = 12;

    // CONDUCTEUR DE BUS \\

    const CONDUCTEUR_PEUT_SE_CIBLER = 13;

    // GARDE DU CORPS \\

    const GARDE_IGNORE_INVULNERABLE = 14;
    const GARDE_INSOIGNABLE = 15;
    const GARDE_NON_CONVERSION_CULTE = 16;

    // INSPECTEUR \\

    const INSPECTEUR_DECOUVRE_ROLE_EXACT = 17;

    // DETECTIVE \\

    const DETECTIVE_IGNORE_IMMUNITE_DETECTION = 18;

    // ESCORT \\

    const ESCORT_INBLOCABLE = 19;
    const ESCORT_DETECTE_INSENSIBLE_BLOCAGE = 20;

    // ESPION \\

    const ESPION_VOIT_CIBLE_MAFIA_TRIADE  = 21;
    const ESPION_VOIT_MEURTRE_MAFIA_TRIADE = 22;

    // JUSTICIER \\

    const JUSTICIER_NOMBRE_DE_TIRS = 23;

    // VEILLEUR \\

    const VEILLEUR_IGNORE_IMMUNITE_DETECTION = 24;
    const VEILLEUR_PEUT_SE_CIBLER = 25;

    // VETERAN \\

    const VETERAN_LIMITE_A_X_NUITS = 26;
    const VETERAN_IGNORE_INVULNERABLE = 27;

    // MAIRE \\

    const MAIRE_PERD_VOTE_SUPP_SI_CULTE = 28;
    const MAIRE_VOTES_COMPTENT_POUR_X = 29;
    const MAIRE_INSOIGNABLE_APRES_DEVO = 30;

    // GARDIEN DE PRISON \\

    const GARDIEN_PEUT_FAIRE_X_EXECUTIONS = 31;

    // MEDECIN LEGISTE \\

    const MEDECIN_ECHOUE_JAMAIS = 32;
    const MEDECIN_DECOUVRE_DERNIERES_VOLONTES = 33;
    const MEDECIN_DECOUVRE_DEATH_TYPE = 34;

    // FRANC MACON \\

    const MACON_DEVIENT_CHEF_QUAND_SEUl = 35;

    // CHEF MACON \\

    const CHEF_MACON_NOMBRE_RECRUTEMENT = 36;

    //-- MAFIA --\\

    // AGENT \\

    const AGENT_DEVIENT_MAFIOSO_QUAND_SEUL = 37;
    const AGENT_NOMBRE_NUITS_ENTRE_PISTAGE = 38;

    // PILLEUR \\

    const PILLEUR_DEVIENT_MAFIOSO_QUAND_SEUL = 39;
    const PILLEUR_PEUT_SE_CACHER_X_FOIS = 40;
    const PILLEUR_CIBLE_ALERTEE = 41;
    const PILLEUR_PEUT_SE_CACHER_CHEZ_MAFIEUX = 42;

    // MAITRE CHANTEUR \\

    const MAITRE_CHANTEUR_DEVIENT_MAFIOSO_QUAND_SEUL = 43;
    const MAITRE_CHANTEUR_VICTIME_PEUT_PARLER_DURANT_JUGEMENT = 44;

    // CONSEILLER \\

    const CONSEILLER_REMPLACE_PARRAIN = 45;
    const CONSEILLER_DETECTE_ROLE_EXACT = 46;
    const CONSEILLER_DEVIENT_MAFIOSO_QUAND_SEUL = 47;

    // PROSTITUEE \\

    const PROSTITUEE_DEVIENT_MAFIOSO_QUAND_SEULE = 48;
    const PROSTITUEE_IMBLOCABLE = 49;
    const PROSTITUEE_DETECTE_CIBLE_IMBLOCABLE = 50;

    // MAITRE_DEGUISEMENT \\

    const MAITRE_DEGUISEMENT_DEVIENT_MAFIOSO_QUAND_SEUL = 51;
    const MAITRE_DEGUISEMENT_MASQUE_ROLE_VICTIME = 52;

    // CONTREFACTEUR \\

    const CONTREFACTEUR_DEVIENT_MAFIOSO_QUAND_SEUL = 53;
    const CONTREFACTEUR_IMMUNISE_DETECTION = 54;

    // PARRAIN \\

    const PARRAIN_INVULNERABLE_LA_NUIT = 55;
    const PARRAIN_IMMUNISE_CONTRE_DETECTIONS = 56;
    const PARRAIN_IMMUNISE_CONTRE_BLOCAGE = 57;
    const PARRAIN_PEUT_TUER_MAFIOSO = 58;

    // CONCIERGE \\

    const CONCIERGE_DEVIENT_MAFIOSO_QUAND_SEUL = 59;
    const CONCIERGE_NOMBRE_MASQUAGES = 60;

    // KIDNAPPER \\

    const KIDNAPPER_DEVIENT_MAFIOSO_QUAND_SEUL = 61;
    const KIDNAPPER_PEUT_EMPRISONNER_MEMBRE_MAFIA = 62;
}