<?php
/**
 * Created by PhpStorm.
 * User: Utilisateur
 * Date: 15/01/2015
 * Time: 22:39
 */

namespace Mafia\RolesBundle\Entity;


abstract class Options_Roles_Enum {

    // SHERRIF \\

    const SHERIFF_DETECT_MAFIA_TRIADE = 0;
    const SHERIFF_DETECT_TUEUR_EN_SERIE = 1;
    const SHERIFF_DETECT_TUEUR_DE_MASSE = 2;
    const SHERIFF_DETECT_PYROMANE = 3;
    const SHERIFF_DETECT_CULTE = 4;

    // CITOYEN \\

    const CITOYEN_GILET_PARE_BALLE = 0;
    const CITOYEN_VICTOIRE_EGALITE_MAFIA = 1;

    // DOCTEUR \\

    const DOCTEUR_SAIT_CIBLE_ATTAQUEE = 0;
    const DOCTEUR_EMPECHE_CONVERSION_CULTE = 1;
    const DOCTEUR_SAIT_CONVERTI_CULTE = 2;
    const DOCTEUR_DEVIENT_SORCIER_SI_CULTE = 3;

    // MARSHALL \\

    const MARSHALL_NOMBRE_LYNCHAGE = 0;
    const MARSHALL_NOMBRE_MORT_PAR_LYNCHAGE = 1;

    // CONDUCTEUR DE BUS \\

    const CONDUCTEUR_PEUT_SE_CIBLER = 0;

    // CRIEUR \\

    const CRIEUR_EXCLU_ALEATOIRE = 0;

    // GARDE DU CORPS \\

    const GARDE_IGNORE_INVULNERABLE = 0;
    const GARDE_INSOIGNABLE = 1;
    const GARDE_NON_CONVERSION_CULTE = 2;

    // INSPECTEUR \\

    const INSPECTEUR_DECOUVRE_ROLE_EXACT = 0;

    // DETECTIVE \\

    const DETECTIVE_IGNORE_IMMUNITE_DETECTION = 0;

    // ESCORT \\

    const ESCORT_INBLOCABLE = 0;
    const ESCORT_DETECTE_INSENSIBLE_BLOCAGE = 1;

    // ESPION \\

    const ESPION_EXCLU_ALEATOIRE = 0;
    const ESPION_VOIT_CIBLE_MAFIA_TRIADE  = 1;
    const ESPION_VOIT_MEURTRE_MAFIA_TRIADE = 2;

    // JUSTICIER \\

    const JUSTICIER_NOMBRE_DE_TIRS = 0;

    // VEILLEUR \\

    const VEILLEUR_IGNORE_IMMUNITE_DETECTION = 0;
    const VEILLEUR_PEUT_SE_CIBLER = 1;

    // VETERAN \\

    const VETERAN_EXCLU_ALEATOIRE = 0;
    const VETERAN_LIMITE_A_X_NUITS = 1;
    const VETERAN_IGNORE_INVULNERABLE = 2;

    // MAIRE \\

    const MAIRE_PERD_VOTE_SUPP_SI_CULTE = 0;
    const MAIRE_VOTES_COMPTENT_POUR_X = 1;
    const MAIRE_INSOIGNABLE_APRES_DEVO = 2;

    // GARDIEN DE PRISON \\

    const GARDIEN_PEUT_FAIRE_X_EXECUTIONS = 0;

    // MEDECIN LEGISTE \\

    const MEDECIN_ECHOUE_JAMAIS = 0;
    const MEDECIN_DECOUVRE_DERNIERES_VOLONTES = 1;
    const MEDECIN_DECOUVRE_DEATH_TYPE = 2;

    // FRANC MACON \\

    const MACON_DEVIENT_CHEF_QUAND_SEUl = 0;

    // CHEF MACON \\

    const CHEF_MACON_EXCLU_ROLE_ALEATOIRE = 0;
    const CHEF_MACON_NOMBRE_RECRUTEMENT = 1;
}