<?php
/**
 * Created by PhpStorm.
 * User: Utilisateur
 * Date: 15/01/2015
 * Time: 22:39
 */

namespace Mafia\RolesBundle\Entity;


abstract class OptionsRolesEnum {


    //-- VILLE --\\

    // SHERRIF \\

    const SHERIFF_DETECT_MAFIA_TRIADE = 0;
    const SHERIFF_DETECT_TUEUR_EN_SERIE = 1;
    const SHERIFF_DETECT_TUEUR_DE_MASSE = 2;
    const SHERIFF_DETECT_PYROMANE = 3;
    const SHERIFF_DETECT_CULTE = 4;

    // CITOYEN \\

    const CITOYEN_GILET_PARE_BALLE = 5;
    const CITOYEN_VICTOIRE_EGALITE_MAFIA = 6;

    // DOCTEUR \\

    const DOCTEUR_SAIT_CIBLE_ATTAQUEE = 7;
    const DOCTEUR_EMPECHE_CONVERSION_CULTE = 8;
    const DOCTEUR_SAIT_CONVERTI_CULTE = 9;
    const DOCTEUR_DEVIENT_SORCIER_SI_CULTE = 10;

    // MARSHALL \\

    const MARSHALL_NOMBRE_LYNCHAGE = 11;
    const MARSHALL_NOMBRE_MORT_PAR_LYNCHAGE = 12;

    // CONDUCTEUR DE BUS \\

    const CONDUCTEUR_PEUT_SE_CIBLER = 13;

    // GARDE DU CORPS \\

    const GARDE_IGNORE_INVULNERABLE = 14;
    const GARDE_INSOIGNABLE = 15;
    const GARDE_NON_CONVERSION_CULTE = 16;

    // INSPECTEUR \\

    const INSPECTEUR_DECOUVRE_ROLE_EXACT = 17;

    // DETECTIVE \\

    const DETECTIVE_IGNORE_IMMUNITE_DETECTION = 18;

    // ESCORT \\

    const ESCORT_INBLOCABLE = 19;
    const ESCORT_DETECTE_INSENSIBLE_BLOCAGE = 20;

    // ESPION \\

    const ESPION_VOIT_CIBLE_MAFIA_TRIADE  = 21;
    const ESPION_VOIT_MEURTRE_MAFIA_TRIADE = 22;

    // JUSTICIER \\

    const JUSTICIER_NOMBRE_DE_TIRS = 23;

    // VEILLEUR \\

    const VEILLEUR_IGNORE_IMMUNITE_DETECTION = 24;
    const VEILLEUR_PEUT_SE_CIBLER = 25;

    // VETERAN \\

    const VETERAN_LIMITE_A_X_NUITS = 26;
    const VETERAN_IGNORE_INVULNERABLE = 27;

    // MAIRE \\

    const MAIRE_PERD_VOTE_SUPP_SI_CULTE = 28;
    const MAIRE_VOTES_COMPTENT_POUR_X = 29;
    const MAIRE_INSOIGNABLE_APRES_DEVO = 30;

    // GARDIEN DE PRISON \\

    const GARDIEN_PEUT_FAIRE_X_EXECUTIONS = 31;

    // MEDECIN LEGISTE \\

    const MEDECIN_ECHOUE_JAMAIS = 32;
    const MEDECIN_DECOUVRE_DERNIERES_VOLONTES = 33;
    const MEDECIN_DECOUVRE_DEATH_TYPE = 34;

    // FRANC MACON \\

    const MACON_DEVIENT_CHEF_QUAND_SEUl = 35;

    // CHEF MACON \\

    const CHEF_MACON_NOMBRE_RECRUTEMENT = 36;

    //-- MAFIA --\\

    // AGENT \\

    const AGENT_DEVIENT_MAFIOSO_QUAND_SEUL = 37;
    const AGENT_NOMBRE_NUITS_ENTRE_PISTAGE = 38;

    // PILLEUR \\

    const PILLEUR_DEVIENT_MAFIOSO_QUAND_SEUL = 39;
    const PILLEUR_PEUT_SE_CACHER_X_FOIS = 40;
    const PILLEUR_CIBLE_ALERTEE = 41;
    const PILLEUR_PEUT_SE_CACHER_CHEZ_MAFIEUX = 42;

    // MAITRE CHANTEUR \\

    const MAITRE_CHANTEUR_DEVIENT_MAFIOSO_QUAND_SEUL = 43;
    const MAITRE_CHANTEUR_VICTIME_PEUT_PARLER_DURANT_JUGEMENT = 44;

    // CONSEILLER \\

    const CONSEILLER_REMPLACE_PARRAIN = 45;
    const CONSEILLER_DETECTE_ROLE_EXACT = 46;
    const CONSEILLER_DEVIENT_MAFIOSO_QUAND_SEUL = 47;

    // PROSTITUEE \\

    const PROSTITUEE_DEVIENT_MAFIOSO_QUAND_SEULE = 48;
    const PROSTITUEE_IMBLOCABLE = 49;
    const PROSTITUEE_DETECTE_CIBLE_IMBLOCABLE = 50;

    // MAITRE_DEGUISEMENT \\

    const MAITRE_DEGUISEMENT_DEVIENT_MAFIOSO_QUAND_SEUL = 51;
    const MAITRE_DEGUISEMENT_MASQUE_ROLE_VICTIME = 52;

    // CONTREFACTEUR \\

    const CONTREFACTEUR_DEVIENT_MAFIOSO_QUAND_SEUL = 53;
    const CONTREFACTEUR_IMMUNISE_DETECTION = 54;

    // PARRAIN \\

    const PARRAIN_INVULNERABLE_LA_NUIT = 55;
    const PARRAIN_IMMUNISE_CONTRE_DETECTIONS = 56;
    const PARRAIN_IMMUNISE_CONTRE_BLOCAGE = 57;
    const PARRAIN_PEUT_TUER_SANS_MAFIOSO = 58;

    // CONCIERGE \\

    const CONCIERGE_DEVIENT_MAFIOSO_QUAND_SEUL = 59;
    const CONCIERGE_NOMBRE_MASQUAGES = 60;

    // KIDNAPPER \\

    const KIDNAPPER_DEVIENT_MAFIOSO_QUAND_SEUL = 61;
    const KIDNAPPER_PEUT_EMPRISONNER_MEMBRE_MAFIA = 62;

    //-- TRIADE --\\

    // ADMINISTRATEUR \\

    const ADMINISTRATEUR_REMPLACE_DRAGON = 63;
    const ADMINISTRATEUR_DETECTE_ROLE_EXACT = 64;
    const ADMINISTRATEUR_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 65;

    // IMPOSTEUR \\

    const IMPOSTEUR_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 66;
    const IMPOSTEUR_PEUT_SE_CACHER_X_FOIS = 67;
    const IMPOSTEUR_CIBLE_ALERTEE = 68;
    const IMPOSTEUR_PEUT_SE_CACHER_CHEZ_TRIADE = 69;

    // DRAGON \\

    const DRAGON_INVULNERABLE_LA_NUIT = 70;
    const DRAGON_IMMUNISE_CONTRE_DETECTIONS = 71;
    const DRAGON_IMMUNISE_CONTRE_BLOCAGE = 72;
    const DRAGON_PEUT_TUER_SANS_TUEUR_A_GAGE = 73;

    // FAUSSAIRE \\

    const FAUSSAIRE_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 74;
    const FAUSSAIRE_IMMUNISE_DETECTION = 75;

    // MAITRE DE L'ENCENS \\

    const MAITRE_ENCENS_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 76;
    const MAITRE_ENCENS_NOMBRE_MASQUAGES = 77;

    // INFORMATEUR \\

    const INFORMATEUR_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 78;
    const INFORMATEUR_MASQUE_ROLE_VICTIME = 79;

    // INTERROGATEUR \\

    const INTERROGATEUR_PEUT_FAIRE_X_EXECUTIONS = 80;

    // LIAISON \\

    const LIAISON_DEVIENT_TUEUR_A_GAGE_QUAND_SEULE = 81;
    const LIAISON_IMBLOCABLE = 82;
    const LIAISON_DETECTE_CIBLE_IMBLOCABLE = 83;

    // MAITRE SILENCE \\

    const MAITRE_SILENCE_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 84;
    const MAITRE_SILENCE_VICTIME_PEUT_PARLER_DURANT_JUGEMENT = 85;

    // AVANT_GARDE \\

    const AVANT_GARDE_DEVIENT_TUEUR_A_GAGE_QUAND_SEUL = 86;
    const AVANT_GARDE_NOMBRE_NUITS_ENTRE_PISTAGE = 87;

    //-- NEUTRE --\\

    // AMNESIQUE \\

    const AMNESIQUE_NOUVEAU_ROLE_REVELE = 88;
    const AMNESIQUE_INAFFILIABLE_VILLE = 89;
    const AMNESIQUE_INAFFILIABLE_MAFIA_TRIADE = 90;
    const AMNESIQUE_NON_ROLE_TUEUR = 91;

    // PYROMANE \\

    const PYROMANE_INCENDIE_TUE_CIBLE_VICTIME = 92;
    const PYROMANE_INCENDIE_TUE_TOUJOURS = 93;
    const PYROMANE_INVULNERABLE_NUIT = 94;
    const PYROMANE_VICTIME_SAIT_MAISON_ARROSEE_ESSENCE = 95;
    const PYROMANE_ARROSE_BLOQUEURS_ROLES = 96;

    // AUDITEUR \\

    const AUDITEUR_CONVERTIT_MAFIA_MAFIOSO = 97;
    const AUDITEUR_CONVERTIT_TRIADE_TUEUR_A_GAGE = 98;
    const AUDITEUR_SI_CIBLE_INVULNERABLE_NUIT_ALORS_NON_CONVERTIBLE = 99;
    const AUDITEUR_LIMITATION_CONVERSIONS = 100;

    // CULTISTE \\

    const CULTISTE_SI_CIBLE_INVULNERABLE_NUIT_ALORS_NON_CONVERTIBLE = 101;
    const CULTISTE_NUITS_ENTRE_CONVERSION = 102;

    // BOURREAU \\

    const BOURREAU_DEVIENT_BOUFFON_APRES_ECHEC = 103;
    const BOURREAU_CIBLE_TOUJOURS_VILLE = 104;
    const BOURREAU_DOIT_SURVIVRE_JUSQUA_FIN = 105;
    const BOURREAU_INVULNERABLE_NUIT = 106;

    // BOUFFON \\

    const BOUFFON_UN_DES_JOUEURS_AYANT_VOTE_MOURRA = 107;

    // JUGE \\

    const JUGE_DEUX_COUR_APPEL_AUTORISEES = 108;
    const JUGE_UN_JOUR_ENTRE_COUR_APPEL = 109;
    const JUGE_VOTE_COMPTE_POUR = 110;

    // TUEUR DE MASSE \\

    const TUEUR_MASSE_INVULNERABLE_NUIT = 111;
    const TUEUR_MASSE_PEUT_SE_CIBLER = 112;
    const TUEUR_MASSE_TEMPS_RECHARGE = 113;
    const TUEUR_MASSE_IMMUNISE_DETECTION = 114;

    // TUEUR EN SERIE \\

    const TUEUR_SERIE_INVULNERABLE_NUIT = 115;
    const TUEUR_SERIE_TUE_BLOQUEUR_ROLE = 116;
    const TUEUR_SERIE_GAGNE_EGALITE_CONTRE_PYROMANE = 117;
    const TUEUR_SERIE_IMMUNISER_DETECTION = 118;

    // SURVIVANT \\

    const SURVIVANT_NOMBRE_GILET_PARE_BALLE = 119;

    // MARIONETTISTE \\

    const MARIONETTISTE_PEUT_SE_RENDRE_CIBLE = 120;
    const MARIONETTISTE_VICTIME_SAIT_CONTROLE = 121;
    const MARIONETTISTE_TRANSFORME_SORCIER_SI_CONVERTI = 122;

    // GOUROU \\

    const SORCIER_LIMITE_SAUVETAGE = 123;
    const SORCIER_NUIT_ECART_ENTRE_SAUVETAGE = 124;



}