<?php

namespace Mafia\RolesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RolesComposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesComposRepository extends EntityRepository
{
}
